sonar.projectKey=RoboC00p_robot-front
sonar.organization=robot-dashboard

# Sources and tests
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.coverage.exclusions=**/*.test.ts,**/*.test.tsx,src/test/**

# Coverage report
sonar.javascript.lcov.reportPaths=coverage/lcov.info
